"""empty message

Revision ID: 708dcdb9dc13
Revises: 
Create Date: 2025-09-08 12:56:29.675617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '708dcdb9dc13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=15), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('promociones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo_promocional', sa.String(length=20), nullable=False),
    sa.Column('descuento_porcentaje', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=False),
    sa.Column('fecha_fin', sa.DateTime(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo_promocional')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('rol', sa.Enum('CLIENTE', 'ADMIN', name='enumrol'), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('clientes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('tipo_documento', sa.Enum('DNI', 'NIE', 'PASAPORTE', name='enumdocument'), nullable=False),
    sa.Column('documento_identidad', sa.String(length=15), nullable=False),
    sa.Column('nombre', sa.String(length=30), nullable=False),
    sa.Column('apellido_paterno', sa.String(length=20), nullable=False),
    sa.Column('apellido_materno', sa.String(length=20), nullable=False),
    sa.Column('genero', sa.Enum('MASCULINO', 'FEMENINO', 'OTROS', 'NINGUNA', name='enumgenero'), nullable=False),
    sa.Column('fecha_nacimiento', sa.DateTime(), nullable=True),
    sa.Column('telefono', sa.String(length=15), nullable=False),
    sa.Column('avatar_url', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('documento_identidad'),
    sa.UniqueConstraint('telefono')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('id_categoria', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=300), nullable=False),
    sa.Column('imagen_url', sa.String(length=300), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_categoria'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('envios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('pais', sa.String(length=15), nullable=False),
    sa.Column('provincia', sa.String(length=20), nullable=False),
    sa.Column('ciudad', sa.String(length=20), nullable=False),
    sa.Column('direccion', sa.String(length=150), nullable=False),
    sa.Column('codigo_postal', sa.String(length=10), nullable=False),
    sa.Column('telefono_contacto', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favoritos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.user_id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(length=300), nullable=False),
    sa.Column('url_imagen', sa.String(length=300), nullable=True),
    sa.Column('rate', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.user_id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('varianteProducto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_producto', sa.Integer(), nullable=False),
    sa.Column('atributo', sa.String(length=50), nullable=False),
    sa.Column('valor', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('stock', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ventas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=False),
    sa.Column('id_envio', sa.Integer(), nullable=False),
    sa.Column('id_promo', sa.Integer(), nullable=True),
    sa.Column('fecha_venta', sa.DateTime(), nullable=False),
    sa.Column('sub_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('descuento_total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('iva_aplicado', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('costo_envio_final', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('total', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('estado_envio', sa.Enum('PENDIENTE', 'EN_TRANSITO', 'ENTREGADO', 'CANCELADO', name='enumestadoenvio'), nullable=False),
    sa.Column('numero_seguimiento', sa.String(length=30), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['clientes.user_id'], ),
    sa.ForeignKeyConstraint(['id_envio'], ['envios.id'], ),
    sa.ForeignKeyConstraint(['id_promo'], ['promociones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detallesVentas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('id_variante_prod', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Integer(), nullable=False),
    sa.Column('precio_unidad', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['id_variante_prod'], ['varianteProducto.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_venta', sa.Integer(), nullable=False),
    sa.Column('fecha_pago', sa.DateTime(), nullable=False),
    sa.Column('monto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('metodo_pago', sa.Enum('TARJETA', 'PAYPAL', name='enummetodopago'), nullable=False),
    sa.Column('token_transaccion', sa.String(length=300), nullable=False),
    sa.Column('ultimos_4_digitos', sa.String(length=4), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'PROCESANDO', 'APROBADO', 'RECHAZADO', 'CANCELADO', 'REEMBOLSADO', 'FALLIDO', name='enumestadopago'), nullable=False),
    sa.Column('detalles', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['id_venta'], ['ventas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagos')
    op.drop_table('detallesVentas')
    op.drop_table('ventas')
    op.drop_table('varianteProducto')
    op.drop_table('reviews')
    op.drop_table('favoritos')
    op.drop_table('envios')
    op.drop_table('productos')
    op.drop_table('clientes')
    op.drop_table('users')
    op.drop_table('promociones')
    op.drop_table('categorias')
    # ### end Alembic commands ###
